[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "hubspot.marketing.emails"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "marketing", "emails"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.marketing.emails"

[build-options]
observabilityIncluded = true
