[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.marketing.emails"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "marketing", "emails"]
# icon = "icon.png" # TODO: Add icon
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.marketing.emails"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true
