[package]
org = "wso2"
name = "bulk_change_reply_email"
version = "0.1.0"
distribution = "2201.10.3"

[build-options]
observabilityIncluded = true

[[dependency]]
org="ballerinax"
name="hubspot.marketing.emails"
version="0.1.0"
repository="local"
